import Knex from 'knex'

export async function seed(knex: Knex){
  await knex('animal').insert([
    {
      fk_localidade: 15,
      fk_classe_bovina: 1,        
      fk_raca: 4,
      nome: '',
      registro: 'x722k',
      classe_registro: 'chip',    
      sexo: 'macho',
      data_n: '2014-03-14',       
      data_m: '2016-04-24',       
      status_: 'morto',
      peso_kg: 1436
    },
    {
      fk_localidade: 1,
      fk_classe_bovina: 1,        
      fk_raca: 15,
      nome: '',
      registro: 'iyknl',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2017-01-22',       
      data_m: '1901-01-01',       
      status_: 'vivo',
      peso_kg: 613
    },
    {
      fk_localidade: 16,
      fk_classe_bovina: 1,        
      fk_raca: 5,
      nome: 'Kiku',
      registro: '',
      classe_registro: 'nome',    
      sexo: 'm',
      data_n: '2019-02-21',       
      data_m: '1901-01-01',       
      status_: 'vivo',
      peso_kg: 1204
    },
    {
      fk_localidade: 10,
      fk_classe_bovina: 1,        
      fk_raca: 3,
      nome: 'Bonner',
      registro: '',
      classe_registro: 'nome',    
      sexo: 'm',
      data_n: '2016-01-14',       
      data_m: '1901-01-01',       
      status_: 'vivo',
      peso_kg: 1016
    },
    {
      fk_localidade: 16,
      fk_classe_bovina: 1,
      fk_raca: 8,
      nome: 'Maninho',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2016-01-12',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 423
    },
    {
      fk_localidade: 22,
      fk_classe_bovina: 1,
      fk_raca: 12,
      nome: 'Trigo',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2016-02-16',
      data_m: '2017-03-11',
      status_: 'morto',
      peso_kg: 402
    },
    {
      fk_localidade: 17,
      fk_classe_bovina: 1,
      fk_raca: 5,
      nome: 'Lazaro',
      registro: '',
      classe_registro: 'nome',
      sexo: 'm',
      data_n: '2018-07-17',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 842
    },
    {
      fk_localidade: 8,
      fk_classe_bovina: 1,
      fk_raca: 13,
      nome: '',
      registro: 'ggc6d',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2015-01-15',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 395
    },
    {
      fk_localidade: 18,
      fk_classe_bovina: 1,
      fk_raca: 17,
      nome: '',
      registro: 'cb8mm',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2016-03-22',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1018
    },
    {
      fk_localidade: 18,
      fk_classe_bovina: 2,
      fk_raca: 10,
      nome: '',
      registro: 'lmki',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2014-02-14',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 718
    },
    {
      fk_localidade: 16,
      fk_classe_bovina: 1,
      fk_raca: 13,
      nome: 'Nino',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2018-08-16',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 985
    },
    {
      fk_localidade: 9,
      fk_classe_bovina: 1,
      fk_raca: 13,
      nome: '',
      registro: 'sjetj',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2017-01-18',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1147
    },
    {
      fk_localidade: 12,
      fk_classe_bovina: 2,
      fk_raca: 15,
      nome: '',
      registro: 'lzmlg',
      classe_registro: 'tatuagem',
      sexo: 'femea',
      data_n: '2019-08-13',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 487
    },
    {
      fk_localidade: 18,
      fk_classe_bovina: 1,
      fk_raca: 8,
      nome: '',
      registro: 'r35j',
      classe_registro: 'chip',
      sexo: 'm',
      data_n: '2014-06-12',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 829
    },
    {
      fk_localidade: 8,
      fk_classe_bovina: 1,
      fk_raca: 6,
      nome: 'Will',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2015-01-20',
      data_m: '2015-08-24',
      status_: 'morto',
      peso_kg: 362
    },
    {
      fk_localidade: 22,
      fk_classe_bovina: 2,
      fk_raca: 14,
      nome: 'Barranca',
      registro: '',
      classe_registro: 'nome',
      sexo: 'femea',
      data_n: '2017-07-24',
      data_m: '2014-01-14',
      status_: 'morto',
      peso_kg: 1286
    },
    {
      fk_localidade: 15,
      fk_classe_bovina: 1,
      fk_raca: 3,
      nome: '',
      registro: '4xcb',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2014-08-12',
      data_m: '2019-05-16',
      status_: 'morto',
      peso_kg: 468
    },
    {
      fk_localidade: 12,
      fk_classe_bovina: 1,
      fk_raca: 16,
      nome: 'Fracasso',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2015-03-11',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 906
    },
    {
      fk_localidade: 8,
      fk_classe_bovina: 2,
      fk_raca: 10,
      nome: 'Mila',
      registro: '',
      classe_registro: 'nome',
      sexo: 'femea',
      data_n: '2015-05-21',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1137
    },
    {
      fk_localidade: 18,
      fk_classe_bovina: 2,
      fk_raca: 11,
      nome: '',
      registro: 'zffy',
      classe_registro: 'tatuagem',
      sexo: 'femea',
      data_n: '2018-03-16',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1019
    },
    {
      fk_localidade: 11,
      fk_classe_bovina: 1,
      fk_raca: 2,
      nome: 'Bidu',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2014-04-23',
      data_m: '2014-06-14',
      status_: 'morto',
      peso_kg: 1098
    },
    {
      fk_localidade: 3,
      fk_classe_bovina: 1,
      fk_raca: 8,
      nome: 'Lesado',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2014-03-23',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 449
    },
    {
      fk_localidade: 5,
      fk_classe_bovina: 1,
      fk_raca: 8,
      nome: '',
      registro: '82a3o',
      classe_registro: 'chip',
      sexo: 'macho',
      data_n: '2018-04-10',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 826
    },
    {
      fk_localidade: 4,
      fk_classe_bovina: 1,
      fk_raca: 13,
      nome: '',
      registro: '3uugl',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2015-04-25',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1487
    },
    {
      fk_localidade: 14,
      fk_classe_bovina: 2,
      fk_raca: 2,
      nome: 'Gisele',
      registro: '',
      classe_registro: 'nome',
      sexo: 'femea',
      data_n: '2015-03-22',
      data_m: '2015-05-23',
      status_: 'morto',
      peso_kg: 1193
    },
    {
      fk_localidade: 16,
      fk_classe_bovina: 1,
      fk_raca: 1,
      nome: '',
      registro: 'h0ol',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2018-07-23',
      data_m: '2014-03-18',
      status_: 'morto',
      peso_kg: 831
    },
    {
      fk_localidade: 6,
      fk_classe_bovina: 1,
      fk_raca: 10,
      nome: '',
      registro: '8igle',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2014-01-24',
      data_m: '2014-02-13',
      status_: 'morto',
      peso_kg: 1298
    },
    {
      fk_localidade: 10,
      fk_classe_bovina: 2,
      fk_raca: 8,
      nome: '',
      registro: 'aizs8',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2018-07-18',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 690
    },
    {
      fk_localidade: 14,
      fk_classe_bovina: 1,
      fk_raca: 5,
      nome: '',
      registro: 'et97l',
      classe_registro: 'tatuagem',
      sexo: 'm',
      data_n: '2014-08-14',
      data_m: '2018-06-11',
      status_: 'morto',
      peso_kg: 495
    },
    {
      fk_localidade: 7,
      fk_classe_bovina: 2,
      fk_raca: 1,
      nome: '',
      registro: '2at0h',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2016-03-25',
      data_m: '2016-03-15',
      status_: 'morto',
      peso_kg: 573
    },
    {
      fk_localidade: 13,
      fk_classe_bovina: 1,
      fk_raca: 5,
      nome: 'Zezinho',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2018-02-18',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 912
    },
    {
      fk_localidade: 17,
      fk_classe_bovina: 1,
      fk_raca: 14,
      nome: 'Esperto',
      registro: '',
      classe_registro: 'nome',
      sexo: 'm',
      data_n: '2019-02-15',
      data_m: '2018-01-24',
      status_: 'morto',
      peso_kg: 1316
    },
    {
      fk_localidade: 6,
      fk_classe_bovina: 1,
      fk_raca: 17,
      nome: 'Virado no Jiraya',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2019-08-19',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 643
    },
    {
      fk_localidade: 19,
      fk_classe_bovina: 1,
      fk_raca: 1,
      nome: 'Zidane',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2018-04-12',
      data_m: '2017-07-11',
      status_: 'morto',
      peso_kg: 1364
    },
    {
      fk_localidade: 17,
      fk_classe_bovina: 2,
      fk_raca: 19,
      nome: '',
      registro: '2h08y',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2016-02-21',
      data_m: '2019-04-12',
      status_: 'morto',
      peso_kg: 666
    },
    {
      fk_localidade: 19,
      fk_classe_bovina: 1,
      fk_raca: 14,
      nome: 'Dinossauro',
      registro: '',
      classe_registro: 'nome',
      sexo: 'm',
      data_n: '2018-06-26',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1022
    },
    {
      fk_localidade: 19,
      fk_classe_bovina: 1,
      fk_raca: 16,
      nome: '',
      registro: 'cbpzb',
      classe_registro: 'tatuagem',
      sexo: 'm',
      data_n: '2016-01-14',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 762
    },
    {
      fk_localidade: 1,
      fk_classe_bovina: 1,
      fk_raca: 13,
      nome: '',
      registro: '745i',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2016-08-12',
      data_m: '2018-03-16',
      status_: 'morto',
      peso_kg: 733
    },
    {
      fk_localidade: 10,
      fk_classe_bovina: 2,
      fk_raca: 5,
      nome: '',
      registro: 'ahes',
      classe_registro: 'chip',
      sexo: 'femea',
      data_n: '2017-03-11',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1014
    },
    {
      fk_localidade: 10,
      fk_classe_bovina: 1,
      fk_raca: 9,
      nome: '',
      registro: '4bt4t',
      classe_registro: 'tatuagem',
      sexo: 'm',
      data_n: '2016-02-19',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1444
    },
    {
      fk_localidade: 8,
      fk_classe_bovina: 1,
      fk_raca: 16,
      nome: '',
      registro: 'tcgul',
      classe_registro: 'chip',
      sexo: 'm',
      data_n: '2018-06-16',
      data_m: '2019-04-12',
      status_: 'morto',
      peso_kg: 766
    },
    {
      fk_localidade: 16,
      fk_classe_bovina: 2,
      fk_raca: 12,
      nome: 'Dálmata',
      registro: '',
      classe_registro: 'nome',
      sexo: 'femea',
      data_n: '2017-07-13',
      data_m: '2017-01-17',
      status_: 'morto',
      peso_kg: 1487
    },
    {
      fk_localidade: 16,
      fk_classe_bovina: 1,
      fk_raca: 3,
      nome: '',
      registro: '8hh9d',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2014-04-12',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 772
    },
    {
      fk_localidade: 15,
      fk_classe_bovina: 1,
      fk_raca: 3,
      nome: 'Hipster',
      registro: '',
      classe_registro: 'nome',
      sexo: 'm',
      data_n: '2017-03-22',
      data_m: '2017-01-10',
      status_: 'morto',
      peso_kg: 903
    },
    {
      fk_localidade: 13,
      fk_classe_bovina: 1,
      fk_raca: 14,
      nome: '',
      registro: '5f6my',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2014-06-10',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 996
    },
    {
      fk_localidade: 3,
      fk_classe_bovina: 1,
      fk_raca: 11,
      nome: 'Danoninha',
      registro: '',
      classe_registro: 'nome',
      sexo: 'femea',
      data_n: '2015-05-13',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 990
    },
    {
      fk_localidade: 14,
      fk_classe_bovina: 1,
      fk_raca: 3,
      nome: '',
      registro: '7bkhu',
      classe_registro: 'chip',
      sexo: 'macho',
      data_n: '2019-03-10',
      data_m: '2017-01-18',
      status_: 'morto',
      peso_kg: 423
    },
    {
      fk_localidade: 4,
      fk_classe_bovina: 1,
      fk_raca: 8,
      nome: '',
      registro: '312q6',
      classe_registro: 'tatuagem',
      sexo: 'macho',
      data_n: '2017-05-23',
      data_m: '2017-04-21',
      status_: 'morto',
      peso_kg: 1101
    },
    {
      fk_localidade: 3,
      fk_classe_bovina: 1,
      fk_raca: 9,
      nome: '',
      registro: 'tg9p',
      classe_registro: 'chip',
      sexo: 'm',
      data_n: '2017-02-22',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 722
    },
    {
      fk_localidade: 8,
      fk_classe_bovina: 1,
      fk_raca: 6,
      nome: '',
      registro: '5578e',
      classe_registro: 'tatuagem',
      sexo: 'm',
      data_n: '2016-05-16',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 796
    },
    {
      fk_localidade: 5,
      fk_classe_bovina: 1,
      fk_raca: 10,
      nome: 'Uivo',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2017-05-26',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 613
    },
    {
      fk_localidade: 18,
      fk_classe_bovina: 1,
      fk_raca: 2,
      nome: '',
      registro: '1pgyu',
      classe_registro: 'tatuagem',
      sexo: 'femea',
      data_n: '2017-08-14',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 505
    },
    {
      fk_localidade: 6,
      fk_classe_bovina: 1,
      fk_raca: 10,
      nome: 'Cometa',
      registro: '',
      classe_registro: 'nome',
      sexo: 'm',
      data_n: '2018-04-26',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 957
    },
    {
      fk_localidade: 15,
      fk_classe_bovina: 1,
      fk_raca: 8,
      nome: 'Felix',
      registro: '',
      classe_registro: 'nome',
      sexo: 'm',
      data_n: '2016-07-12',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1240
    },
    {
      fk_localidade: 9,
      fk_classe_bovina: 1,
      fk_raca: 2,
      nome: '',
      registro: 'fwh97',
      classe_registro: 'chip',
      sexo: 'm',
      data_n: '2014-01-20',
      data_m: '2017-01-15',
      status_: 'morto',
      peso_kg: 1493
    },
    {
      fk_localidade: 4,
      fk_classe_bovina: 2,
      fk_raca: 12,
      nome: 'Nina',
      registro: '',
      classe_registro: 'nome',
      sexo: 'femea',
      data_n: '2016-02-23',
      data_m: '2016-03-25',
      status_: 'morto',
      peso_kg: 1405
    },
    {
      fk_localidade: 7,
      fk_classe_bovina: 1,
      fk_raca: 16,
      nome: 'Cookie',
      registro: '',
      classe_registro: 'nome',
      sexo: 'macho',
      data_n: '2017-02-19',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1197
    },
    {
      fk_localidade: 1,
      fk_classe_bovina: 1,
      fk_raca: 12,
      nome: '',
      registro: '87y5',
      classe_registro: 'chip',
      sexo: 'm',
      data_n: '2015-07-15',
      data_m: '2015-01-19',
      status_: 'morto',
      peso_kg: 672
    },
    {
      fk_localidade: 6,
      fk_classe_bovina: 1,
      fk_raca: 12,
      nome: '',
      registro: 'zayei',
      classe_registro: 'tatuagem',
      sexo: 'm',
      data_n: '2017-04-14',
      data_m: '1901-01-01',
      status_: 'vivo',
      peso_kg: 1243
    },
    {
      fk_localidade: 21,
      fk_classe_bovina: 2,
      fk_raca: 6,
      nome: '',
      registro: 'cbnij',
      classe_registro: 'tatuagem',
      sexo: 'femea',
      data_n: '2018-07-23',
      data_m: '2015-02-24',
      status_: 'morto',
      peso_kg: 905
    }
  ]);
}